[tool.poetry]
name = "overlay-risk"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.2,<3.10"
eth-brownie = "^1.14.6"
pandas = "^1.2.3"
numpy = "^1.20.2"
scipy = "^1.6.2"
influxdb-client = {extras = ["ciso"], version = "^1.16.0"}
click = "^7.1.2"
schedule = "^1.1.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
